### ISSUE TITLE
paypal-adaptive-hoops-0.5.0.0 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [fanjam/paypal-adaptive-hoops#5]
Some source code files seems to be missing from the release tarball: 

    Preprocessing test suite 'unit' for paypal-adaptive-hoops-0.5.0.0...

    tests/Test.hs:2:8:
        Could not find module ‘Unit.Money’
        Use -v to see a list of the files searched for.

    tests/Test.hs:3:8:
        Could not find module ‘Unit.Parser’
        Use -v to see a list of the files searched for.

The complete build log is at http://hydra.cryp.to/build/502330/nixlog/2/raw.

**Comment by seagreen** [comment]
Thanks for the note. Just pushed a [new version](https://hackage.haskell.org/package/paypal-adaptive-hoops-0.5.1.0) to Hackage with a hopefully [fixed cabal file](https://github.com/fanjam/paypal-adaptive-hoops/commit/dc132ca9a875edcc5a681daafdc4368e524830b3).

**Comment by seagreen** [comment]
@peti Do you know how I can look up details on Hydra's attempts to build this package? Hackage now show's the Hydra tried to my fixed version of paypal-adaptive-hoops, but the link to the Hydra job is dead: http://hydra.nixos.org/job/nixpkgs/haskell-updates/haskellngPackages.paypal-adaptive-hoops.x86_64-linux

Thanks again for the help.

**Comment by peti** [comment]
@seagreen, the links on Hackage are updated immediately when build instructions for the package are committed to our repository. In case of `paypal-adaptive-hoops`, that happened on [2015-01-21](https://github.com/NixOS/nixpkgs/commit/e558d0e49b7e45e70c700ae86c740d2232463c29#diff-e4ed6fefa9564bfd27ee249e42e145e2R87483). Hydra is lagging behind those commits, unfortunately, so it may take 1-2 days until it catches up with the changes. According to http://hydra.nixos.org/jobset/nixpkgs/haskell-updates, Hydra's last evaluation of the package set happened on 2015-01-20, so `paypal-adaptive-hoops` is not yet part of the CI system. Give it a couple of hours, then the page Hackage refers to will appear automatically.

**Comment by peti** [comment]
One more thing: it would be nice to include `lens 4.7` in the list of acceptable build dependencies: http://packdeps.haskellers.com/feed?needle=exact%3Apaypal-adaptive-hoops. The package builds fine after the constraints have been edited out of the Cabal file.

**Comment by seagreen** [comment]
Sounds good. I pushed a new version with `lens >= 4.6 && < 4.8` to hackage, and will close this issue once paypal-adaptive-hoops makes it successfully through Hydra. Thanks for your work on nixpkgs!
